/* Palette color codes */
/* Palette URL: http://paletton.com/#uid=35a120krwvacfLCkz-6vNoyF9hh */
/* Generated by Paletton.com © 2002_2014 */
/* http://paletton.com */

/* As hex codes */
var color = {
  // Main Priary color - Magenta
  primary_0 : '#C71C7D',
  primary_1 : '#E78FC0',
  primary_2 : '#D34B98',
  primary_3 : '#9D0159',
  primary_4 : '#6E003E',

  // Seconary color 1 - Blue
  secondary1_0 : '#1A7E9A',
  secondary1_1 : '#84C0D1',
  secondary1_2 : '#4194AB',
  secondary1_3 : '#05607A',
  secondary1_4 : '#024356',

  // Secondary color 2 - Yellow
  secondary2_0 : '#F8CD23',
  secondary2_1 : '#FFEB9E',
  secondary2_2 : '#FFDE5B',
  secondary2_3 : '#C39C01',
  secondary2_4 : '#8A6E00',

  pink : '#df6260',
  red : '#900'
}

module.exports = color;

/* As RGBa codes */
/*
.rgba-primary_0 { color: rgba(199, 28,125,1) }	// Main Primary color
.rgba-primary_1 { color: rgba(231,143,192,1) }
.rgba-primary_2 { color: rgba(211, 75,152,1) }
.rgba-primary_3 { color: rgba(157,  1, 89,1) }
.rgba-primary_4 { color: rgba(110,  0, 62,1) }

.rgba-secondary_1_0 { color: rgba( 26,126,154,1) }	// Main Secondary color (1)
.rgba-secondary_1_1 { color: rgba(132,192,209,1) }
.rgba-secondary_1_2 { color: rgba( 65,148,171,1) }
.rgba-secondary_1_3 { color: rgba(  5, 96,122,1) }
.rgba-secondary_1_4 { color: rgba(  2, 67, 86,1) }

.rgba-secondary_2_0 { color: rgba(248,205, 35,1) }	// Main Secondary color (2)
.rgba-secondary_2_1 { color: rgba(255,235,158,1) }
.rgba-secondary_2_2 { color: rgba(255,222, 91,1) }
.rgba-secondary_2_3 { color: rgba(195,156,  1,1) }
.rgba-secondary_2_4 { color: rgba(138,110,  0,1) }
*/
